### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 1462: character maps to <undefined>

### ISSUE THREAD

**Issue by secure-77** [TheDauntless/patch-apk#6]
Hi 👋 
Nice, that someone is maintaining this repo further.

I am getting the following error, any idea what I can do?

```text
[+] Disassembling split APKs |################################| 4/4

[+] Rebuilding as a single APK
Traceback (most recent call last):
  File "D:\patch-apk\patch-apk\patch-apk.py", line 684, in <module>
    main()
  File "D:\patch-apk\patch-apk\patch-apk.py", line 39, in main
    apkfile = getTargetAPK(pkgname, apkpaths, tmppath, args.disable_styles_hack, args.extract_only)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\patch-apk\patch-apk\patch-apk.py", line 326, in getTargetAPK
    return combineSplitAPKs(pkgname, localapks, tmppath, disableStylesHack, extract_only)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\patch-apk\patch-apk\patch-apk.py", line 387, in combineSplitAPKs
    build(baseapkdir)
  File "D:\patch-apk\patch-apk\patch-apk.py", line 214, in build
    fixPrivateResources(baseapkdir)
  File "D:\patch-apk\patch-apk\patch-apk.py", line 204, in fixPrivateResources
    rawREReplace(os.path.join(root, f), '@android', '@*android')
  File "D:\patch-apk\patch-apk\patch-apk.py", line 637, in rawREReplace
    contents = file.read()
               ^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 1462: character maps to <undefined>
```

**Comment by secure-77** [comment]
Was able to fix the error by adding utf-8 encoding to this block: https://github.com/TheDauntless/patch-apk/blob/0458b8bae4844c95d96d6c01dcd7330de964180d/patch-apk.py#L630-L641

```python
def rawREReplace(path, pattern, replacement):
    if os.path.exists(path):
        contents = ""
        with open(path, 'r', encoding="utf8") as file:
            contents = file.read()
        newContents = re.sub(pattern, replacement, contents)
        if (contents != newContents):
            dbgPrint("\n[~] Patching " + path)
            with open(path, 'w', encoding="utf8") as file:
                file.write(newContents)
    else:
        abort("\nError: Failed to find file at " + path + " for pattern replacement")
```
